[package]
name = "FinSc-Topology"
version = "0.3.1"
ipkg = "FinSc-Topology.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Multiset-Ternary]
type = "local"
path = "../FinSc-Multiset-Ternary"
ipkg = "FinSc-Multiset-Ternary.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"
